services:

  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    volumes:
      - ${UPLOAD_LOCATION:-library}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${IMMICH_PORT:-2283}:2283
    env_file: .env
    healthcheck:
      disable: false
    depends_on:
      - redis
      - database

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    volumes:
      - model-cache:/cache
    env_file: .env
    healthcheck:
      disable: false

  redis:
    image: docker.io/redis:${REDIS_TAG:-6.2-alpine}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    image: docker.io/tensorchord/pgvecto-rs:${PGVECTO_TAG:-pg14-v0.2.0}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION:-db-data}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]

volumes:
  library:
  db-data:
  model-cache:
